steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t','us-central1-docker.pkg.dev/mcmp-integration-qa/mend-bolt/myimage:latest', '.']
    
  - name: 'us-central1-docker.pkg.dev/mcmp-integration-qa/mend-bolt/myimage:latest'
    args: ['curl', '-s', '-L', '-O', 'https://github.com/whitesource/unified-agent-distribution/raw/master/standAlone/wss_agent.sh']

  # - name: 'gcr.io/cloud-builders/gsutil'
  #   args: ['cp', 'gitleaks-report.json', 'gs://testingleaks/gitleaks-report.json']
  
  # - name: 'ubuntu'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       report= cat /workspace/gitleaks-report.json
  #       echo $report
  #       if [ "$report" = "[]" ]; then
  #         echo "No leaks found. Continuing build."
  #       else
  #         echo "Leaks detected. Failing build."
  #         exit 1
  #       fi
        
  
# artifacts:
#   objects:
#     location: 'gs://gitleaks-scan-report/'  # Update this with your bucket name
#     paths: ['gitleaks-report.json']

      
