steps:
  # - name: 'gcr.io/cloud-builders/git'
  #   args:
  #     - 'clone'
  #     - 'https://github.com/shlokie1999/MoviePilot'
  #     - '/workspace/source'
      
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['pull', 'zricethezav/gitleaks:latest']

  # - name: 'gcr.io/cloud-builders/docker'
  #   args:
  #     - 'run'
  #     - '-v'
  #     - '/workspace/source:/path'
  #     - 'zricethezav/gitleaks:latest'
  #     - 'detect'
  #     - '--source=/path'
  #     - '--exit-code=0'
  #     - '--report-path'
  #     - 'gitleaks-report.json'
  
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y wget tar golang 
        wget https://github.com/zricethezav/gitleaks/releases/download/v8.15.3/gitleaks_8.15.3_linux_x64.tar.gz
        mkdir gitleaks
        tar -xvzf gitleaks_8.15.3_linux_x64.tar.gz
        chmod +x gitleaks
        mv gitleaks /usr/bin/
        gitleaks -h
        gitleaks detect --source . -v --report-path gitleaks-report.json
        ls /workspace
        
artifacts:
  objects:
    location: 'gs://gitleaks-scan-report/'  # Update this with your bucket name
    paths: ['gitleaks-report.json']

      
