steps:
  - name: 'gcr.io/cloud-builders/git'
    args:
      - 'clone'
      - 'https://github.com/shlokie1999/MoviePilot'
      - '/workspace/source'

  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y wget tar golang git
        wget https://github.com/zricethezav/gitleaks/releases/download/v8.15.3/gitleaks_8.15.3_linux_x64.tar.gz #Download the release 
        mkdir gitleaks
        tar -xvzf gitleaks_8.15.3_linux_x64.tar.gz
        chmod +x gitleaks # Set permision
        mv gitleaks /usr/bin/
        gitleaks -h  # Support for command flags
        gitleaks detect --source /workspace/source -v --report-path /workspace/gitleaks-report.json --exit-code 0 --redact --no-git # Run Gitleaks Command

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gitleaks-report.json', 'gs://clair_scan_report_bucket/gitleaks-report.json']
  
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        report= cat /workspace/gitleaks-report.json
        echo $report
        if [ "$report" = "[]" ]; then
          echo "No leaks found. Continuing build."
        else
          echo "Leaks detected. Failing build."
          exit 1
        fi
        
  
# artifacts:
#   objects:
#     location: 'gs://gitleaks-scan-report/'  # Update this with your bucket name
#     paths: ['gitleaks-report.json']

      
